//
//  ViewController.m
//  SelfSizingTable
//
//  Created by 温商贷 on 8/25/16.
//  Copyright © 2016 曹航. All rights reserved.
//

#import "ViewController.h"
#import "TestTableViewCell.h"
#import "Test2TableViewCell.h"

@interface ViewController ()
@property (weak, nonatomic) IBOutlet UITableView *tableView;

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
    
    _tableView.dataSource = self;
    _tableView.delegate = self;
    
    _tableView.estimatedRowHeight = 85.0;
    _tableView.rowHeight = UITableViewAutomaticDimension;

}

- (CGFloat)tableView:(UITableView *)tableView heightForFooterInSection:(NSInteger)section {
    return 0.1;
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    return 4;
}

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView {
    return 1;
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    
    if (indexPath.row == 3) {
        
        Test2TableViewCell *cell = [_tableView dequeueReusableCellWithIdentifier:@"cell2"];
        
        return cell;
    }
    
    TestTableViewCell *cell = [_tableView dequeueReusableCellWithIdentifier:@"cell1"];

    cell.lbl.text = @"(Edit: After your XIB is generated by XCode, it contains an empty UIView, but we need a UITableViewCell; so you have to manually remove the UIView and insert a Table View Cell. Of course, IB will not show any UITableViewCell parameters for a UIView.)";
    
    return cell;
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

@end
